ServerSide1_KontaktBogEksempel/Models/ContactInfo.cs
using System.Security.Cryptography;
using System.Text;

namespace ServerSide1_KontaktBogEksempel.Models
{
    public class ContactInfo
    {

        public int ContactId { get; set; }

        public required string Name { get; set; }

        public required string Email { get; set; }

        public string Phone { get; set; } = string.Empty;

        public string Description { get; set; } = string.Empty;

        public string Address { get; set; } = string.Empty;

        public string City { get; set; } = string.Empty;

        public string DefaultImage { 
            get {
                using MD5 md5 = MD5.Create();
                byte[] data = Encoding.UTF8.GetBytes(Email);

                data = md5.ComputeHash(data);

                string hash = BitConverter.ToString(data);

                return $"https://robohash.org/{hash}.png?set=set3";
            }
        }

        public string ImagePath = string.Empty;
    }
}

ServerSide1_KontaktBogEksempel/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ServerSide1_KontaktBogEksempel.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ServerSide1_KontaktBogEksempel/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ServerSide1_KontaktBogEksempel.Models;
using ServerSide1_KontaktBogEksempel.Services;

namespace ServerSide1_KontaktBogEksempel.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IContactService _ContactService;

        public List<ContactInfo> Contacts { get; set; } = new List<ContactInfo>();

        public IndexModel(IContactService contactService)
        {
            _ContactService = contactService;
        }

        public void OnGet()
        {
            Contacts = _ContactService.GetContacts();
        }
    }
}

ServerSide1_KontaktBogEksempel/Pages/NewContact.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Hosting.Internal;
using ServerSide1_KontaktBogEksempel.Models;
using ServerSide1_KontaktBogEksempel.Services;

namespace ServerSide1_KontaktBogEksempel.Pages
{
    public class NewContactModel : PageModel
    {

        private IContactService _contactService;

        public NewContactModel(IContactService contactService)
        {
            _contactService = contactService;
        }

        [BindProperty]
        public ContactInfo? Contact { get; set; }

        [BindProperty]
        public IFormFile? ContactPicture { get; set; }

        public void OnGet() {}

        public async Task<IActionResult> OnPost() 
        {
            if (Contact != null)
            {
                if (ContactPicture != null)
                {

                    string FullPath = Path.Combine(Path.GetFullPath("wwwroot"),"Images",ContactPicture.FileName);

                    FileStream file = System.IO.File.Create(FullPath);
                    await ContactPicture.CopyToAsync(file);
                    file.Close();

                    Contact.ImagePath = Path.Combine("Images",ContactPicture.FileName);
                }

                _contactService.AddContact(Contact);
                return RedirectToPage("/Index");

                
            }
            else
            {
                return Page();
            }
        }
    }
}

ServerSide1_KontaktBogEksempel/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServerSide1_KontaktBogEksempel.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ServerSide1_KontaktBogEksempel/ViewComponents/ContactCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using ServerSide1_KontaktBogEksempel.Services;

namespace ServerSide1_KontaktBogEksempel.ViewComponents
{
    [ViewComponent]
    public class ContactCountViewComponent : ViewComponent
    {

        private IContactService _ContactService;

        public ContactCountViewComponent(IContactService contactService)
        {
            _ContactService = contactService;
        }

        public Task<ViewViewComponentResult> InvokeAsync()
        {
            int count = _ContactService.GetContactCount();

            return Task.FromResult(View(count));
        }
    }
}

ServerSide1_KontaktBogEksempel/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<a asp-page="NewContact" class="btn btn-primary btn-sm">Ny kontakt</a>

<partial name="ContactList" model="Model.Contacts" />

ServerSide1_KontaktBogEksempel/Pages/NewContact.cshtml
@page
@model ServerSide1_KontaktBogEksempel.Pages.NewContactModel

<h1>Ny kontakt</h1>

<form method="post" enctype="multipart/form-data">
    <div class="form-group">
      <label for="Name">Navn</label>
      <input type="text" asp-for="Contact.Name" class="form-control" id="Name" placeholder="Indtast navn">
    </div>
    <div class="form-group">
      <label for="Email">Email</label>
      <input type="email" asp-for="Contact.Email" class="form-control" id="Email" placeholder="Indtast email">
    </div>
    <div class="form-group">
        <label for="Phone">Telefon</label>
        <input type="tel" asp-for="Contact.Phone"  class="form-control" id="Phone" placeholder="Indtast Telefonnummer">
    </div>
    <div class="form-group">
        <label for="Address">Adresse</label>
        <input type="text" asp-for="Contact.Address" class="form-control" id="Address" placeholder="Optionel">
    </div>
    <div class="form-group">
        <label for="City">By</label>
        <input type="text" asp-for="Contact.City" class="form-control" id="City" placeholder="Optionel">
    </div>
    <div class="form-group">
        <label for="Description">Beskrivelse</label>
        <textarea asp-for="Contact.Description" class="form-control" id="Description" rows="3" placeholder="Optionel"></textarea>
    </div>
    <div class="form-group">
        <label for="Image">KontaktBillede</label>
        <input type="file" class="form-control-file" name="ContactPicture" id="Image">
    </div>
  <button type="submit" class="btn btn-primary">Gem</button>
</form>

ServerSide1_KontaktBogEksempel/Pages/PartialViews/ContactList.cshtml
@model List<ContactInfo>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Billede</th>
            <th scope="col">Navn</th>
            <th scope="col">Email</th>
            <th scope="col">Mobil</th>
        </tr>
    </thead>
    <tbody>
        @foreach (ContactInfo contact in Model)
        {
            @Html.Partial("ContactListElement",contact)
        }
    </tbody>
</table>

ServerSide1_KontaktBogEksempel/Pages/PartialViews/ContactListElement.cshtml
@using ServerSide1_KontaktBogEksempel.Models
@model ContactInfo

<tr>

    <th scope="row">
        @if (string.IsNullOrWhiteSpace(Model.ImagePath))
        {
            <img class="contact-thumbnail contact-DefaultImage" src="@Model.DefaultImage" />
        }
        else
        {
            <img class="contact-thumbnail" src="@Model.ImagePath" />
        }
    </th>
    <td>@Model.Name</td>
    <td>@Model.Email</td>
    <td>@Model.Phone</td>
</tr>

ServerSide1_KontaktBogEksempel/Pages/Shared/Components/ContactCount/Default.cshtml
@model int

Kontakter: @Model

ServerSide1_KontaktBogEksempel/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ServerSide1_KontaktBogEksempel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ServerSide1_KontaktBogEksempel.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ServerSide1_KontaktBogEksempel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark">
                               @await Component.InvokeAsync("ContactCount")
                               @* <vc:ContactCount></vc:ContactCount>*@
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ServerSide1_KontaktBogEksempel - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>